name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
    - name: Get source
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install mod_spatialite (Linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install -y libsqlite3-mod-spatialite

    - name: Install mod_spatialite (Mac OS)
      if: ${{ matrix.os == 'macOS-latest' }}
      run: brew install libspatialite
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: '1'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Pack
      run: dotnet pack -c Release --no-build -o artifacts -p:NoWarn=NU5105

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: NuGet Package Files (${{ matrix.os }})
        path: artifacts
